package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHdxVehiclesTrips<M extends BaseHdxVehiclesTrips<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setVehicleId(Long vehicleId) {
		set("vehicleId", vehicleId);
		return (M)this;
	}

	public Long getVehicleId() {
		return get("vehicleId");
	}

	public M setDeviceSn(String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public String getDeviceSn() {
		return get("deviceSn");
	}

	public M setTripId(Long tripId) {
		set("trip_Id", tripId);
		return (M)this;
	}

	public Long getTripId() {
		return get("trip_Id");
	}

	public M setAverageFuelEconomy(java.math.BigDecimal averageFuelEconomy) {
		set("average_fuel_economy", averageFuelEconomy);
		return (M)this;
	}

	public java.math.BigDecimal getAverageFuelEconomy() {
		return get("average_fuel_economy");
	}

	public M setAverageSpeed(java.math.BigDecimal averageSpeed) {
		set("average_speed", averageSpeed);
		return (M)this;
	}

	public java.math.BigDecimal getAverageSpeed() {
		return get("average_speed");
	}

	public M setFuelFee(java.math.BigDecimal fuelFee) {
		set("fuel_fee", fuelFee);
		return (M)this;
	}

	public java.math.BigDecimal getFuelFee() {
		return get("fuel_fee");
	}

	public M setHighestSpeed(java.math.BigDecimal highestSpeed) {
		set("highest_speed", highestSpeed);
		return (M)this;
	}

	public java.math.BigDecimal getHighestSpeed() {
		return get("highest_speed");
	}

	public M setMileage(Integer mileage) {
		set("mileage", mileage);
		return (M)this;
	}

	public Integer getMileage() {
		return get("mileage");
	}

	public M setPending(Boolean pending) {
		set("pending", pending);
		return (M)this;
	}

	public Boolean getPending() {
		return get("pending");
	}

	public M setPointTripBegin(String pointTripBegin) {
		set("point_trip_begin", pointTripBegin);
		return (M)this;
	}

	public String getPointTripBegin() {
		return get("point_trip_begin");
	}

	public M setPointTripEnd(String pointTripEnd) {
		set("point_trip_end", pointTripEnd);
		return (M)this;
	}

	public String getPointTripEnd() {
		return get("point_trip_end");
	}

	public M setSpeedBarUrl(String speedBarUrl) {
		set("speed_bar_url", speedBarUrl);
		return (M)this;
	}

	public String getSpeedBarUrl() {
		return get("speed_bar_url");
	}

	public M setSuddenAccelerationCount(Integer suddenAccelerationCount) {
		set("sudden_acceleration_count", suddenAccelerationCount);
		return (M)this;
	}

	public Integer getSuddenAccelerationCount() {
		return get("sudden_acceleration_count");
	}

	public M setSuddenBrakeCount(Integer suddenBrakeCount) {
		set("sudden_brake_count", suddenBrakeCount);
		return (M)this;
	}

	public Integer getSuddenBrakeCount() {
		return get("sudden_brake_count");
	}

	public M setSuddenTurningCount(Integer suddenTurningCount) {
		set("sudden_turning_count", suddenTurningCount);
		return (M)this;
	}

	public Integer getSuddenTurningCount() {
		return get("sudden_turning_count");
	}

	public M setTimeTripBegin(java.util.Date timeTripBegin) {
		set("time_trip_begin", timeTripBegin);
		return (M)this;
	}

	public java.util.Date getTimeTripBegin() {
		return get("time_trip_begin");
	}

	public M setTimeTripEnd(java.util.Date timeTripEnd) {
		set("time_trip_end", timeTripEnd);
		return (M)this;
	}

	public java.util.Date getTimeTripEnd() {
		return get("time_trip_end");
	}

	public M setTotalFuelEconomy(java.math.BigDecimal totalFuelEconomy) {
		set("total_fuel_economy", totalFuelEconomy);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFuelEconomy() {
		return get("total_fuel_economy");
	}

	public M setGpsOnly(Boolean gpsOnly) {
		set("gps_only", gpsOnly);
		return (M)this;
	}

	public Boolean getGpsOnly() {
		return get("gps_only");
	}

}
