package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasCollide<M extends BaseAdasCollide<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setDeviceSn(String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public String getDeviceSn() {
		return get("deviceSn");
	}

	public M setEventid(Long eventid) {
		set("eventid", eventid);
		return (M)this;
	}

	public Long getEventid() {
		return get("eventid");
	}

	public M setEventtime(java.util.Date eventtime) {
		set("eventtime", eventtime);
		return (M)this;
	}

	public java.util.Date getEventtime() {
		return get("eventtime");
	}

	public M setGPSDataCount(Integer GPSDataCount) {
		set("GPSDataCount", GPSDataCount);
		return (M)this;
	}

	public Integer getGPSDataCount() {
		return get("GPSDataCount");
	}

	public M setSenserCount(Integer SenserCount) {
		set("SenserCount", SenserCount);
		return (M)this;
	}

	public Integer getSenserCount() {
		return get("SenserCount");
	}

	public M setGPSDatas(String GPSDatas) {
		set("GPSDatas", GPSDatas);
		return (M)this;
	}

	public String getGPSDatas() {
		return get("GPSDatas");
	}

	public M setSenserDatas(String SenserDatas) {
		set("SenserDatas", SenserDatas);
		return (M)this;
	}

	public String getSenserDatas() {
		return get("SenserDatas");
	}

}
