package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasEmergencySenser<M extends BaseAdasEmergencySenser<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setDeviceSn(String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public String getDeviceSn() {
		return get("deviceSn");
	}

	public M setEventid(Long eventid) {
		set("eventid", eventid);
		return (M)this;
	}

	public Long getEventid() {
		return get("eventid");
	}

	public M setOccurtime(java.util.Date occurtime) {
		set("occurtime", occurtime);
		return (M)this;
	}

	public java.util.Date getOccurtime() {
		return get("occurtime");
	}

	public M setAccelerationX(Integer accelerationX) {
		set("accelerationX", accelerationX);
		return (M)this;
	}

	public Integer getAccelerationX() {
		return get("accelerationX");
	}

	public M setAccelerationY(Integer accelerationY) {
		set("accelerationY", accelerationY);
		return (M)this;
	}

	public Integer getAccelerationY() {
		return get("accelerationY");
	}

	public M setAccelerationZ(Integer accelerationZ) {
		set("accelerationZ", accelerationZ);
		return (M)this;
	}

	public Integer getAccelerationZ() {
		return get("accelerationZ");
	}

	public M setGyroscopeX(Long gyroscopeX) {
		set("gyroscopeX", gyroscopeX);
		return (M)this;
	}

	public Long getGyroscopeX() {
		return get("gyroscopeX");
	}

	public M setGyroscopeY(Long gyroscopeY) {
		set("gyroscopeY", gyroscopeY);
		return (M)this;
	}

	public Long getGyroscopeY() {
		return get("gyroscopeY");
	}

	public M setGyroscopeZ(Long gyroscopeZ) {
		set("gyroscopeZ", gyroscopeZ);
		return (M)this;
	}

	public Long getGyroscopeZ() {
		return get("gyroscopeZ");
	}

}
