package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasCycledata<M extends BaseAdasCycledata<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setDeviceSn(String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public String getDeviceSn() {
		return get("deviceSn");
	}

	public M setValtage(java.math.BigDecimal valtage) {
		set("valtage", valtage);
		return (M)this;
	}

	public java.math.BigDecimal getValtage() {
		return get("valtage");
	}

	public M setRate1(Integer rate1) {
		set("rate1", rate1);
		return (M)this;
	}

	public Integer getRate1() {
		return get("rate1");
	}

	public M setRate2(Integer rate2) {
		set("rate2", rate2);
		return (M)this;
	}

	public Integer getRate2() {
		return get("rate2");
	}

	public M setRate3(Integer rate3) {
		set("rate3", rate3);
		return (M)this;
	}

	public Integer getRate3() {
		return get("rate3");
	}

	public M setRate4(Integer rate4) {
		set("rate4", rate4);
		return (M)this;
	}

	public Integer getRate4() {
		return get("rate4");
	}

	public M setSpeed1(Integer speed1) {
		set("speed1", speed1);
		return (M)this;
	}

	public Integer getSpeed1() {
		return get("speed1");
	}

	public M setSpeed2(Integer speed2) {
		set("speed2", speed2);
		return (M)this;
	}

	public Integer getSpeed2() {
		return get("speed2");
	}

	public M setSpeed3(Integer speed3) {
		set("speed3", speed3);
		return (M)this;
	}

	public Integer getSpeed3() {
		return get("speed3");
	}

	public M setSpeed4(Integer speed4) {
		set("speed4", speed4);
		return (M)this;
	}

	public Integer getSpeed4() {
		return get("speed4");
	}

	public M setTemperater(Integer temperater) {
		set("temperater", temperater);
		return (M)this;
	}

	public Integer getTemperater() {
		return get("temperater");
	}

	public M setLpk1(java.math.BigDecimal lpk1) {
		set("lpk1", lpk1);
		return (M)this;
	}

	public java.math.BigDecimal getLpk1() {
		return get("lpk1");
	}

	public M setLpk2(java.math.BigDecimal lpk2) {
		set("lpk2", lpk2);
		return (M)this;
	}

	public java.math.BigDecimal getLpk2() {
		return get("lpk2");
	}

	public M setLpk3(java.math.BigDecimal lpk3) {
		set("lpk3", lpk3);
		return (M)this;
	}

	public java.math.BigDecimal getLpk3() {
		return get("lpk3");
	}

	public M setLpk4(java.math.BigDecimal lpk4) {
		set("lpk4", lpk4);
		return (M)this;
	}

	public java.math.BigDecimal getLpk4() {
		return get("lpk4");
	}

	public M setTotalODO(Integer TotalODO) {
		set("TotalODO", TotalODO);
		return (M)this;
	}

	public Integer getTotalODO() {
		return get("TotalODO");
	}

	public M setLeftOil(Integer LeftOil) {
		set("LeftOil", LeftOil);
		return (M)this;
	}

	public Integer getLeftOil() {
		return get("LeftOil");
	}

	public M setErrorCount(Integer ErrorCount) {
		set("ErrorCount", ErrorCount);
		return (M)this;
	}

	public Integer getErrorCount() {
		return get("ErrorCount");
	}

	public M setErrorCodes(String ErrorCodes) {
		set("ErrorCodes", ErrorCodes);
		return (M)this;
	}

	public String getErrorCodes() {
		return get("ErrorCodes");
	}

	public M setGPSDataCount(Integer GPSDataCount) {
		set("GPSDataCount", GPSDataCount);
		return (M)this;
	}

	public Integer getGPSDataCount() {
		return get("GPSDataCount");
	}

	public M setSenserDataCount(Integer SenserDataCount) {
		set("SenserDataCount", SenserDataCount);
		return (M)this;
	}

	public Integer getSenserDataCount() {
		return get("SenserDataCount");
	}

	public M setOccurtime(java.util.Date occurtime) {
		set("occurtime", occurtime);
		return (M)this;
	}

	public java.util.Date getOccurtime() {
		return get("occurtime");
	}

	public M setGPSDatas(String GPSDatas) {
		set("GPSDatas", GPSDatas);
		return (M)this;
	}

	public String getGPSDatas() {
		return get("GPSDatas");
	}

	public M setSenserDatas(String SenserDatas) {
		set("SenserDatas", SenserDatas);
		return (M)this;
	}

	public String getSenserDatas() {
		return get("SenserDatas");
	}

}
