package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasWarning<M extends BaseAdasWarning<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setDeviceSn(String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public String getDeviceSn() {
		return get("deviceSn");
	}

	public M setEventid(Long eventid) {
		set("eventid", eventid);
		return (M)this;
	}

	public Long getEventid() {
		return get("eventid");
	}

	public M setEventtime(java.util.Date eventtime) {
		set("eventtime", eventtime);
		return (M)this;
	}

	public java.util.Date getEventtime() {
		return get("eventtime");
	}

	public M setFCWEvent(Integer FCWEvent) {
		set("FCWEvent", FCWEvent);
		return (M)this;
	}

	public Integer getFCWEvent() {
		return get("FCWEvent");
	}

	public M setHMWTime(Integer HMWTime) {
		set("HMWTime", HMWTime);
		return (M)this;
	}

	public Integer getHMWTime() {
		return get("HMWTime");
	}

	public M setVDistance(Integer VDistance) {
		set("VDistance", VDistance);
		return (M)this;
	}

	public Integer getVDistance() {
		return get("VDistance");
	}

	public M setLLDistance(Integer LLDistance) {
		set("LLDistance", LLDistance);
		return (M)this;
	}

	public Integer getLLDistance() {
		return get("LLDistance");
	}

	public M setRLDistance(Integer RLDistance) {
		set("RLDistance", RLDistance);
		return (M)this;
	}

	public Integer getRLDistance() {
		return get("RLDistance");
	}

	public M setPDWEvent(Integer PDWEvent) {
		set("PDWEvent", PDWEvent);
		return (M)this;
	}

	public Integer getPDWEvent() {
		return get("PDWEvent");
	}

	public M setPDistance(Integer PDistance) {
		set("PDistance", PDistance);
		return (M)this;
	}

	public Integer getPDistance() {
		return get("PDistance");
	}

}
