package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasTrips<M extends BaseAdasTrips<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return get("id");
	}

	public M setDeviceSn(String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public String getDeviceSn() {
		return get("deviceSn");
	}

	public M setTripId(String tripId) {
		set("trip_Id", tripId);
		return (M)this;
	}

	public String getTripId() {
		return get("trip_Id");
	}

	public M setAverageSpeed(Integer averageSpeed) {
		set("average_speed", averageSpeed);
		return (M)this;
	}

	public Integer getAverageSpeed() {
		return get("average_speed");
	}

	public M setHighestRate(Integer highestRate) {
		set("highest_rate", highestRate);
		return (M)this;
	}

	public Integer getHighestRate() {
		return get("highest_rate");
	}

	public M setHighestSpeed(Integer highestSpeed) {
		set("highest_speed", highestSpeed);
		return (M)this;
	}

	public Integer getHighestSpeed() {
		return get("highest_speed");
	}

	public M setMileage(Integer mileage) {
		set("mileage", mileage);
		return (M)this;
	}

	public Integer getMileage() {
		return get("mileage");
	}

	public M setPointTripBegin(String pointTripBegin) {
		set("point_trip_begin", pointTripBegin);
		return (M)this;
	}

	public String getPointTripBegin() {
		return get("point_trip_begin");
	}

	public M setPointTripEnd(String pointTripEnd) {
		set("point_trip_end", pointTripEnd);
		return (M)this;
	}

	public String getPointTripEnd() {
		return get("point_trip_end");
	}

	public M setSuddenAccelerationCount(Integer suddenAccelerationCount) {
		set("sudden_acceleration_count", suddenAccelerationCount);
		return (M)this;
	}

	public Integer getSuddenAccelerationCount() {
		return get("sudden_acceleration_count");
	}

	public M setSuddenBrakeCount(Integer suddenBrakeCount) {
		set("sudden_brake_count", suddenBrakeCount);
		return (M)this;
	}

	public Integer getSuddenBrakeCount() {
		return get("sudden_brake_count");
	}

	public M setSuddenTurningCount(Integer suddenTurningCount) {
		set("sudden_turning_count", suddenTurningCount);
		return (M)this;
	}

	public Integer getSuddenTurningCount() {
		return get("sudden_turning_count");
	}

	public M setTimeTripBegin(java.util.Date timeTripBegin) {
		set("time_trip_begin", timeTripBegin);
		return (M)this;
	}

	public java.util.Date getTimeTripBegin() {
		return get("time_trip_begin");
	}

	public M setTimeTripEnd(java.util.Date timeTripEnd) {
		set("time_trip_end", timeTripEnd);
		return (M)this;
	}

	public java.util.Date getTimeTripEnd() {
		return get("time_trip_end");
	}

	public M setTotalFuelEconomy(java.math.BigDecimal totalFuelEconomy) {
		set("total_fuel_economy", totalFuelEconomy);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFuelEconomy() {
		return get("total_fuel_economy");
	}

	public M setLatitudeBegin(java.math.BigDecimal latitudeBegin) {
		set("latitude_begin", latitudeBegin);
		return (M)this;
	}

	public java.math.BigDecimal getLatitudeBegin() {
		return get("latitude_begin");
	}

	public M setLongtitueBegin(java.math.BigDecimal longtitueBegin) {
		set("longtitue_begin", longtitueBegin);
		return (M)this;
	}

	public java.math.BigDecimal getLongtitueBegin() {
		return get("longtitue_begin");
	}

	public M setLatitudeEnd(java.math.BigDecimal latitudeEnd) {
		set("latitude_end", latitudeEnd);
		return (M)this;
	}

	public java.math.BigDecimal getLatitudeEnd() {
		return get("latitude_end");
	}

	public M setLongtitueEnd(java.math.BigDecimal longtitueEnd) {
		set("longtitue_end", longtitueEnd);
		return (M)this;
	}

	public java.math.BigDecimal getLongtitueEnd() {
		return get("longtitue_end");
	}

	public M setTotalFuel(java.math.BigDecimal totalFuel) {
		set("total_fuel", totalFuel);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFuel() {
		return get("total_fuel");
	}

	public M setIdleTime(Integer idleTime) {
		set("idle_time", idleTime);
		return (M)this;
	}

	public Integer getIdleTime() {
		return get("idle_time");
	}

	public M setDriveTime(Integer driveTime) {
		set("drive_time", driveTime);
		return (M)this;
	}

	public Integer getDriveTime() {
		return get("drive_time");
	}

}
