package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasSenserdata<M extends BaseAdasSenserdata<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setDeviceSn(java.lang.String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public java.lang.String getDeviceSn() {
		return get("deviceSn");
	}

	public M setEventid(java.lang.Long eventid) {
		set("eventid", eventid);
		return (M)this;
	}

	public java.lang.Long getEventid() {
		return get("eventid");
	}

	public M setOccurtime(java.util.Date occurtime) {
		set("occurtime", occurtime);
		return (M)this;
	}

	public java.util.Date getOccurtime() {
		return get("occurtime");
	}

	public M setAccelerationX(java.lang.Integer accelerationX) {
		set("accelerationX", accelerationX);
		return (M)this;
	}

	public java.lang.Integer getAccelerationX() {
		return get("accelerationX");
	}

	public M setAccelerationY(java.lang.Integer accelerationY) {
		set("accelerationY", accelerationY);
		return (M)this;
	}

	public java.lang.Integer getAccelerationY() {
		return get("accelerationY");
	}

	public M setAccelerationZ(java.lang.Integer accelerationZ) {
		set("accelerationZ", accelerationZ);
		return (M)this;
	}

	public java.lang.Integer getAccelerationZ() {
		return get("accelerationZ");
	}

	public M setGyroscopeX(java.lang.Long gyroscopeX) {
		set("gyroscopeX", gyroscopeX);
		return (M)this;
	}

	public java.lang.Long getGyroscopeX() {
		return get("gyroscopeX");
	}

	public M setGyroscopeY(java.lang.Long gyroscopeY) {
		set("gyroscopeY", gyroscopeY);
		return (M)this;
	}

	public java.lang.Long getGyroscopeY() {
		return get("gyroscopeY");
	}

	public M setGyroscopeZ(java.lang.Long gyroscopeZ) {
		set("gyroscopeZ", gyroscopeZ);
		return (M)this;
	}

	public java.lang.Long getGyroscopeZ() {
		return get("gyroscopeZ");
	}

}
