package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasEmergency<M extends BaseAdasEmergency<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setDeviceSn(java.lang.String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public java.lang.String getDeviceSn() {
		return get("deviceSn");
	}

	public M setEventtype(java.lang.Integer eventtype) {
		set("eventtype", eventtype);
		return (M)this;
	}

	public java.lang.Integer getEventtype() {
		return get("eventtype");
	}

	public M setEventtime(java.lang.Integer eventtime) {
		set("eventtime", eventtime);
		return (M)this;
	}

	public java.lang.Integer getEventtime() {
		return get("eventtime");
	}

	public M setGPSDataCount(java.lang.Integer GPSDataCount) {
		set("GPSDataCount", GPSDataCount);
		return (M)this;
	}

	public java.lang.Integer getGPSDataCount() {
		return get("GPSDataCount");
	}

	public M setSenserCount(java.lang.Integer SenserCount) {
		set("SenserCount", SenserCount);
		return (M)this;
	}

	public java.lang.Integer getSenserCount() {
		return get("SenserCount");
	}

	public M setGPSDatas(java.lang.String GPSDatas) {
		set("GPSDatas", GPSDatas);
		return (M)this;
	}

	public java.lang.String getGPSDatas() {
		return get("GPSDatas");
	}

	public M setSenserDatas(java.lang.String SenserDatas) {
		set("SenserDatas", SenserDatas);
		return (M)this;
	}

	public java.lang.String getSenserDatas() {
		return get("SenserDatas");
	}

}
