package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHdxTripsTask<M extends BaseHdxTripsTask<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setLastGatherTime(java.util.Date lastGatherTime) {
		set("last_gather_time", lastGatherTime);
		return (M)this;
	}

	public java.util.Date getLastGatherTime() {
		return get("last_gather_time");
	}

}
