package com.cws.alarm.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdasCycledata<M extends BaseAdasCycledata<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setDeviceSn(java.lang.String deviceSn) {
		set("deviceSn", deviceSn);
		return (M)this;
	}

	public java.lang.String getDeviceSn() {
		return get("deviceSn");
	}

	public M setValtage(java.math.BigDecimal valtage) {
		set("valtage", valtage);
		return (M)this;
	}

	public java.math.BigDecimal getValtage() {
		return get("valtage");
	}

	public M setRate1(java.lang.Integer rate1) {
		set("rate1", rate1);
		return (M)this;
	}

	public java.lang.Integer getRate1() {
		return get("rate1");
	}

	public M setRate2(java.lang.Integer rate2) {
		set("rate2", rate2);
		return (M)this;
	}

	public java.lang.Integer getRate2() {
		return get("rate2");
	}

	public M setRate3(java.lang.Integer rate3) {
		set("rate3", rate3);
		return (M)this;
	}

	public java.lang.Integer getRate3() {
		return get("rate3");
	}

	public M setRate4(java.lang.Integer rate4) {
		set("rate4", rate4);
		return (M)this;
	}

	public java.lang.Integer getRate4() {
		return get("rate4");
	}

	public M setSpeed1(java.lang.Integer speed1) {
		set("speed1", speed1);
		return (M)this;
	}

	public java.lang.Integer getSpeed1() {
		return get("speed1");
	}

	public M setSpeed2(java.lang.Integer speed2) {
		set("speed2", speed2);
		return (M)this;
	}

	public java.lang.Integer getSpeed2() {
		return get("speed2");
	}

	public M setSpeed3(java.lang.Integer speed3) {
		set("speed3", speed3);
		return (M)this;
	}

	public java.lang.Integer getSpeed3() {
		return get("speed3");
	}

	public M setSpeed4(java.lang.Integer speed4) {
		set("speed4", speed4);
		return (M)this;
	}

	public java.lang.Integer getSpeed4() {
		return get("speed4");
	}

	public M setTemperater(java.lang.Integer temperater) {
		set("temperater", temperater);
		return (M)this;
	}

	public java.lang.Integer getTemperater() {
		return get("temperater");
	}

	public M setLpk1(java.math.BigDecimal lpk1) {
		set("lpk1", lpk1);
		return (M)this;
	}

	public java.math.BigDecimal getLpk1() {
		return get("lpk1");
	}

	public M setLpk2(java.math.BigDecimal lpk2) {
		set("lpk2", lpk2);
		return (M)this;
	}

	public java.math.BigDecimal getLpk2() {
		return get("lpk2");
	}

	public M setLpk3(java.math.BigDecimal lpk3) {
		set("lpk3", lpk3);
		return (M)this;
	}

	public java.math.BigDecimal getLpk3() {
		return get("lpk3");
	}

	public M setLpk4(java.math.BigDecimal lpk4) {
		set("lpk4", lpk4);
		return (M)this;
	}

	public java.math.BigDecimal getLpk4() {
		return get("lpk4");
	}

	public M setTotalODO(java.lang.Integer TotalODO) {
		set("TotalODO", TotalODO);
		return (M)this;
	}

	public java.lang.Integer getTotalODO() {
		return get("TotalODO");
	}

	public M setLeftOil(java.lang.Integer LeftOil) {
		set("LeftOil", LeftOil);
		return (M)this;
	}

	public java.lang.Integer getLeftOil() {
		return get("LeftOil");
	}

	public M setErrorCount(java.lang.Integer ErrorCount) {
		set("ErrorCount", ErrorCount);
		return (M)this;
	}

	public java.lang.Integer getErrorCount() {
		return get("ErrorCount");
	}

	public M setErrorCodes(java.lang.String ErrorCodes) {
		set("ErrorCodes", ErrorCodes);
		return (M)this;
	}

	public java.lang.String getErrorCodes() {
		return get("ErrorCodes");
	}

	public M setGPSDataCount(java.lang.Integer GPSDataCount) {
		set("GPSDataCount", GPSDataCount);
		return (M)this;
	}

	public java.lang.Integer getGPSDataCount() {
		return get("GPSDataCount");
	}

	public M setSenserDataCount(java.lang.Integer SenserDataCount) {
		set("SenserDataCount", SenserDataCount);
		return (M)this;
	}

	public java.lang.Integer getSenserDataCount() {
		return get("SenserDataCount");
	}

	public M setOccurtime(java.util.Date occurtime) {
		set("occurtime", occurtime);
		return (M)this;
	}

	public java.util.Date getOccurtime() {
		return get("occurtime");
	}

	public M setGPSDatas(java.lang.String GPSDatas) {
		set("GPSDatas", GPSDatas);
		return (M)this;
	}

	public java.lang.String getGPSDatas() {
		return get("GPSDatas");
	}

	public M setSenserDatas(java.lang.String SenserDatas) {
		set("SenserDatas", SenserDatas);
		return (M)this;
	}

	public java.lang.String getSenserDatas() {
		return get("SenserDatas");
	}

}
