package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasEmergency;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasEmergency extends BaseAdasEmergency<AdasEmergency> {
	public static final AdasEmergency dao = new AdasEmergency().dao();
}
