package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasGpsdata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasGpsdata extends BaseAdasGpsdata<AdasGpsdata> {
	public static final AdasGpsdata dao = new AdasGpsdata().dao();
}
