package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasAlarm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasAlarm extends BaseAdasAlarm<AdasAlarm> {
	public static final AdasAlarm dao = new AdasAlarm().dao();
}
