package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasWarning;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasWarning extends BaseAdasWarning<AdasWarning> {
	public static final AdasWarning dao = new AdasWarning().dao();
}
