package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasCycledata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasCycledata extends BaseAdasCycledata<AdasCycledata> {
	public static final AdasCycledata dao = new AdasCycledata().dao();
}
