package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasCollideGps;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasCollideGps extends BaseAdasCollideGps<AdasCollideGps> {
	public static final AdasCollideGps dao = new AdasCollideGps().dao();
}
