package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasEmergencySenser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasEmergencySenser extends BaseAdasEmergencySenser<AdasEmergencySenser> {
	public static final AdasEmergencySenser dao = new AdasEmergencySenser().dao();
}
