package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasCollide;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasCollide extends BaseAdasCollide<AdasCollide> {
	public static final AdasCollide dao = new AdasCollide().dao();
}
