package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasEmergencyGps;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasEmergencyGps extends BaseAdasEmergencyGps<AdasEmergencyGps> {
	public static final AdasEmergencyGps dao = new AdasEmergencyGps().dao();
}
