package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasSenserdata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasSenserdata extends BaseAdasSenserdata<AdasSenserdata> {
	public static final AdasSenserdata dao = new AdasSenserdata().dao();
}
