package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasCollideSenser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasCollideSenser extends BaseAdasCollideSenser<AdasCollideSenser> {
	public static final AdasCollideSenser dao = new AdasCollideSenser().dao();
}
