package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseAdasTrips;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdasTrips extends BaseAdasTrips<AdasTrips> {
	public static final AdasTrips dao = new AdasTrips().dao();
}
