package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseHdxTripsTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HdxTripsTask extends BaseHdxTripsTask<HdxTripsTask> {
	public static final HdxTripsTask dao = new HdxTripsTask().dao();
}
