package com.cws.alarm.model;

import com.cws.alarm.model.base.BaseHdxVehiclesTrips;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HdxVehiclesTrips extends BaseHdxVehiclesTrips<HdxVehiclesTrips> {
	public static final HdxVehiclesTrips dao = new HdxVehiclesTrips().dao();
	public boolean ExistTripId(Long trip_id)
	{
		List<HdxVehiclesTrips> hdxVehiclesTripses = dao.find("select 1 from hdx_vehicles_trips where trip_id = ?", trip_id);
		if (hdxVehiclesTripses.size()>0)
			return  true;
		else return  false;
	}
}
